import type { Diagnosis, NormalizedFailure } from "../platforms/types.js";

export type IssueStatus = "open" | "merged" | "pending_review" | "escalated" | "reverted";

export interface IssueRecord {
  id: number;
  slug: string;
  path: string;
  repo: string;
  branch: string;
  title: string;
  status: IssueStatus;
  confidence: number;
  ticketId?: string;
  summary: string;
  diagnosis: string;
  markdown: string;
  fixId: number;
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 48);
}

export function generateIssueRecordMarkdown(
  fixId: number,
  failure: NormalizedFailure,
  diagnosis: Diagnosis,
  diff: string,
  status: IssueStatus,
  confidence: number,
  ticketId?: string,
): IssueRecord {
  const slug = slugify(diagnosis.rootCause.split(".")[0] ?? "issue");
  const path = `.stitch/issues/${fixId}-${slug}.md`;
  const title = diagnosis.rootCause.split(".")[0] ?? "CI failure";

  const markdown = `# Issue #${fixId}: ${title}

**Repo:** \`${failure.repo}\` · **Branch:** \`${failure.branch}\`  
**Status:** ${status} · **Confidence:** ${confidence}%  
${ticketId ? `**Ticket:** ${ticketId}\n` : ""}
## Summary

${diagnosis.rootCause}

## Diagnosis (GPT-5.6)

${diagnosis.explanation}

## Likely files

${diagnosis.likelyFiles.map((f) => `- \`${f}\``).join("\n")}

## Diff

\`\`\`diff
${diff.trim()}
\`\`\`

---
_Generated by Stitch · ${new Date().toISOString()}_
`;

  return {
    id: fixId,
    slug,
    path,
    repo: failure.repo,
    branch: failure.branch,
    title,
    status,
    confidence,
    ticketId,
    summary: diagnosis.rootCause,
    diagnosis: diagnosis.explanation,
    markdown,
    fixId,
  };
}
